import { v4 as uuidv4 } from 'uuid';
import slugify from 'slugify';

export const animeList = () => {
  return [
    'Inu x Boku SS',
    'Seto no Hanayome',
    'Shugo Chara!! Doki',
    'Princess Tutu',
    'Bakuman. 3rd Season',
    'Yume-iro Pâtissière',
    'Ultra Maniac',
    'Shakugan no Shana II (Second)',
    'Nodame Cantabile: Paris-hen',
    'Ouran Koukou Host Club',
    'Junjou Romantica 2',
    'Kaichou wa Maid-sama!',
    'Sekaiichi Hatsukoi 2',
    'Tonari no Kaibutsu-kun',
    'Bleach',
    'Chobits',
    'Kimi ni Todoke',
    'Naruto: Shippuuden',
    'Ranma ½',
    'Toradora!',
    'Bakuman. 2nd Season',
    'Gakuen Alice',
    'Skip Beat!',
    'Chihayafuru 2',
    'Shounen Onmyouji',
    'Chihayafuru',
    'Itazura na Kiss',
    'Beelzebub',
    'Hanasakeru Seishounen',
    'SKET Dance',
    'B-gata H-kei',
    'Crayon Shin-chan',
    'Fruits Basket',
    'Saiunkoku Monogatari',
    'One Piece',
    'Glass no Kamen (2005)',
    'Air Gear',
    'Saiunkoku Monogatari 2nd Season',
    'InuYasha',
    'Chu-Bra!!',
    'Nodame Cantabile Finale',
    'Ghost Hunt',
    'Accel World',
    'Bakuman.',
    'Nodame Cantabile',
    'Kamisama Hajimemashita',
    'Cardcaptor Sakura',
    'Daa! Daa! Daa!',
    'Kimi ni Todoke 2nd Season',
    'Sekaiichi Hatsukoi',
    'Code-E',
    'Junjou Romantica',
    'Kiniro no Corda: Primo Passo',
    'D.Gray-man Hallow',
    'Sengoku☆Paradise Kiwami',
    'Peace Maker Kurogane Movie 1: Omou Michi',
    'Boku wa Kuma',
    'Ane Koi: Suki Kirai Daisuki.',
    'Parasol Henbei',
    'Ginga Hyouryuu Vifam: Kieta 12-nin',
    'Super Danganronpa 2.5: Komaeda Nagito to Sekai no Hakaimono',
    'Chuuhai Lemon: Love 30s - Ame ni Nurete mo',
    'Juuni Kokuki',
    'Diabolik Lovers OVA',
    'Ko Ko Ro',
    'Tuzki: Love Assassin',
    'Lupin III: Lupin Ikka Seizoroi',
    'Neko Konogoro',
    'Ao no 6-gou',
    'Ben-To Picture Drama',
    'Gasshin Sentai Mechander Robo',
    'Seikai no Monshou Special',
    'Tegamibachi Gakuen',
    'Oniku Daisuki! Zeushi-kun: Suteki na Hamburger',
    'Soul Buster',
    'Mobile Suit Gundam: Zeonic Front - Indignation of Zeon.',
    'Karakuri Circus',
    'Nanumu no Ie',
    'Death Billiards',
    'Fake Style II',
    'Live On Cardliver Kakeru',
    'Gegege no Kitarou: Saikyou Youkai Gundan! Nippon Jouriku!!',
    'Kokudo Oh',
    'Triage X',
    'Shinkai no Kantai: Submarine 707',
    'Densha Kamo Shirenai',
    'Ylion to Callysia',
    'Nanatsu no Bitoku',
    'Metropolis (2009)',
    'Hai to Gensou no Grimgar Special',
    'Medamayaki no Kimi Itsu Tsubusu?',
    'Watashi no Ashinaga Ojisan Specials',
    'Duel Masters Movie 1: Yami no Shiro no Maryuuou',
    'Bounty Dog: Getsumen no Ibu',
    'Hurricane Live! 2033',
    'Densetsu no Yuusha no Densetsu: Iris Report',
    'Aisai Nikki',
    'Chikyuu Shoujo Arjuna',
    'Peeping Life 5.0ch',
    'K-On!!',
    'Haru wo Daite Ita',
    'Pokemon 3D Adventure 2: Pikachu no Kaitei Daibouken',
    'Soredemo Machi wa Mawatteiru',
    'Makkuro na Obentou',
    'Code Geass: Hangyaku no Lelouch Picture Drama - Hajimari no Zenya',
    'Scan2Go',
    '3 Choume no Tama: Onegai! Momo-chan wo Sagashite!!',
    'Shokuzai no Kyoushitsu',
    'Majokko Shimai no Yoyo to Nene',
    'Yuu☆Yuu☆Hakusho Special',
    'Bernard-jou Iwaku.',
    'Himitsu no Akko-chan (Movie)',
    'Calihara no Uta',
    'Aoi Umi no Tristia',
    'Dae Jang Geum: Jang Geum&#039;s Dream',
    'Space☆Dandy',
    'Tetsuwan Atom: Ivan no Wakusei - Robot to Ningen no Yuujou',
    'Ohi-sama to Kaeru',
    'Nanatsu no Taizai OVA',
    'Ribbon no Kishi (1999)',
    'Aoki Hagane no Arpeggio: Ars Nova',
    'ClassicaLoid 2nd Season',
    'Juvenile Pornography The Animation',
    'Ichigo Ichie: Koibana Tomobana',
    'Doraemon: Time Machine de Oshougatsu',
    'Chirin no Suzu',
    'MD Geist II: Death Force',
    'Re:Creators',
    'Hajimari no Boukensha-tachi: Legend of Crystania',
    'Magical Music Train',
    'Rekka no Honoo',
    'Cosmic Fantasy: Ginga Mehyou no Wana',
    'Hibike! Euphonium',
    'Gintama.: Shirogane no Tamashii-hen',
    'Gun-dou Musashi',
    'Yaseruyagi',
    'Galactic Patrol Lensman',
    'Denki-gai no Honya-san',
    'MaxValu Kyushu',
    'Uchi no 3 Shimai',
    'Kuroko no Basket: Oshaberi Demo Shimasen ka',
    'Cross Road',
    'Hourou Musuko Specials',
    'Koi to Uso OVA',
    'Esper Mami: Hoshizora no Dancing Doll',
    'Carol & Tuesday',
    'Akai Shouzou: Char, Soshite Frontal e',
    'Gakkatsu! 2nd Season',
    'Tsuru no Sugomori',
    'Selector Infected WIXOSS',
    'Hane (2016)',
    'Gokujo.: Gokurakuin Joshikou Ryou Monogatari',
    'Bannou Bunka Neko-Musume Specials',
    'Ultra B',
    'Saint☆Oniisan (Movie)',
    'Makai Tenshi Djibril',
    'Supernatural The Animation',
    'Soukan Yuugi',
    'Andromeda Stories',
    'Houkago Initiation',
    'ACCA: 13-ku Kansatsu-ka',
    'Future GPX Cyber Formula: Early Days Renewal',
    'Dennou Sentai Voogie&#039;s★Angel Gaiden: Susume! Super★Angels!',
    'Gokuu no Daibouken',
    'Kitty to Daniel no Suteki na Christmas',
    'Alice to Zouroku',
    'Micchiri Neko',
    'Slayers',
    'Seikaisuru Kado',
    'Dragon Ball Super',
    'Genshiken Nidaime Specials',
    'Shinshaku Sengoku Eiyuu Densetsu: Sanada Juu Yuushi The Animation',
    'Shiro Hon',
    'Yama no Susume',
    'Kuroinu: Kedakaki Seijo wa Hakudaku ni Somaru',
    'Princess Principal',
    'Nyanpire The Animation',
    'Kira Kira 5th Anniversary Live Anime: Kick Start Generation',
    'Tenpou Ibun: Ayakashi Ayashi',
    'Pokopon no Yukai na Saiyuuki',
    'Persona 4 the Animation',
    'Fate/stay night Movie: Unlimited Blade Works',
    'Udauda Yatteru Hima wa Nee!',
    'Boku dake no Hentai Kanojo The Animation',
    'Menghuan Xiyou',
    'Luv Wave',
    'Lupin III: Seven Days Rhapsody',
    'Sidonia no Kishi 3',
    'Ski Jumping Pairs: Road to Torino 2006',
    'Nazotoki-hime wa Meitantei♥',
    'Thermae Romae x LOFT Collaboration',
    'Fairy Tail',
    'Marvel Future Avengers',
    'Chalk-iro no People',
    'Super Seisyun Brothers',
    'Baku Ane: Otouto Shibocchau zo! The Animation',
    'Sei Shoujo The Animation',
    'Ryoujoku Guerrilla Kari 3',
    'Ore ga Kanojo wo *su Wake',
    'Seto no Hanayome Fan Disc',
    'Momo Kyun Sword',
    'Bust to Bust: Chichi wa Chichi ni',
    'Onara Gorou',
    'A-Size Classmate',
    'Taikong Lixianji',
    'Kono Minikuku mo Utsukushii Sekai',
    'Go! Go! 575',
    'Daybreak Interlude',
    'Mezzo Forte',
    'Shirahata no Shoujo Ryuuko',
    'Master Keaton',
    'Choujin Densetsu Urotsukidouji: Mirai-hen',
    'Shoujo kara Shoujo e...',
    'Angel&#039;s Feather',
    'Busou Shoujo Machiavellianism: Doki! "Goken-darake" no Ian Ryokou',
    'Platonic Chain: Ansatsu Jikkouchuu',
    'Shugo Chara! Party!',
    'Devilman Memorial',
    'Working&#039;!!',
    'Haikara-san ga Tooru',
    'Henbou Moral Hazard',
    'Dolphin Ouji',
    'Samayou Midara na Lunatics',
    'Pochacco no Jack to Mame no Ki',
    'Nintama Rantarou Movie',
    'Naruto: Takigakure no Shitou - Ore ga Eiyuu Dattebayo!',
    'Meshimase Lodoss-tou Senki: Sorette Oishii no?',
    'Dragon Ball Specials',
    'Treasure Gaust',
    'Ar:pieL - 6-seosgaeui Unmyeong',
    'Petit Eva: Evangelion@School',
    'City Hunter: Kinkyuu Namachuukei!? Kyouakuhan Saeba Ryou no Saigo',
    'Binan Koukou Chikyuu Boueibu LOVE!',
    'Tatamp',
    'Gongnyong Baengmannyeon Ttori',
    'Ghiblies',
    'WWW.Working!!',
    'Balloon',
    'Girlfriend (Note)',
    'Yamiyo no Jidaigeki',
    'Shin Mitsubachi Maya no Bouken',
    'R.O.D the TV',
    'Mahou no Star Magical Emi: Finale! Finale!',
    'Osamishi Tani no Wakare Uta',
    'Kuroko no Basket: Baka ja Katenai no yo!',
    'Hacka Doll The Animation',
    'Dr. Slump: Arale-chan Specials',
    'Ranma ½: 1994 Music Calendar',
    'Yami no Purple Eye',
    'Anime Koukyoushi: Jungle Taitei',
    'Akai Koudan Zillion: Utahime Yakyoku',
    'Sore Ike! Anpanman: Kirakira Boshi no Namida',
    'Konna Watashitachi ga Nariyuki de Heroine ni Natta Kekka www',
    'Nezumi-kun no Chokki',
    'Defend Love',
    'Apache Yakyuugun',
    'Good Morning!!! Doronjo',
    'Kiss x Sis (TV)',
    'Koto no Shidai',
    'Ganbare! Marine Kid',
    'Kanojo x Kanojo x Kanojo: Sanshimai to no DokiDoki Kyoudou Seikatsu',
    'Dr. Slump: Hoyoyo! Arale no Himitsu Dai Koukai dayo!!',
    'Tick Tock',
    'Kanzen Mushusei: Sorezore no Houkago',
    'Crayon Shin-chan x Panpaka Pants: Aeon Cinema Manner Movie Collab',
    'Yakin Byoutou Ni',
    'Tennis no Ouji-sama',
    'Egao',
    'Raldessia Chronicles',
    'Gunnm',
    'Velvet Underworld: Alternative',
    'Ukkari Pénélope (2009)',
    'Akai Kiba: Blue Sonnet',
    'The Aurora: Umi no Aurora',
    'Kami nomi zo Shiru Sekai: Natsu-iro Surprise',
    'Beat Shot!!',
    'T7S Longing for Summer Again and Again: Harukaze',
    'Detective Conan Movie 21: The Crimson Love Letter',
    'Kakko Kawaii Sengen!',
    'Punky Funky Baby',
    'Na mo Nai Hana no Youni',
    'Mechakko Dotakon',
    'Hello Kitty no Yume no Oshiro no Ouji-sama',
    'Zettai Karen Children OVA: Aitazousei! Ubawareta Mirai?',
    'Raja Maharaja',
    'Ranma ½: DoCo Music Video',
    'Umbrella Fighter!',
    'Akai Jitensha',
    'Zhan Long Si Qu',
    'Tang Lang Bu Chan',
    'To Heart 2 AD Plus',
    'Donna Donna',
    'Gundress',
    'Ojamajo Doremi Dokkaan!',
    'Danna ga Nani wo Itteiru ka Wakaranai Ken',
    'Igano Kabamaru',
    'Mobile Suit Gundam Unicorn RE:0096',
    'Hataraku Maou-sama!',
    'Shin Maple Town Monogatari: Palm Town-hen - Konnichiwa! Atarashii Machi',
    'D.C.II S.S.: Da Capo II Second Season',
    'Kurogane no Linebarrels Picture Drama',
    'Landscape',
    'Only You: Viva! Cabaret Club',
    'Bakuretsu Tenshi: Infinity',
    'Fairy Tail Movie 1: Houou no Miko - Hajimari no Asa',
    'Dominion',
    'Darker than Black: Kuro no Keiyakusha',
    'Teekyuu',
    'Aoi Bungaku Series',
    'Glass no Kamen Desu ga to Z',
    'Mofa Ya Ma',
    'Natsuyuki Rendezvous',
    'Mobile Suit Zeta Gundam: A New Translation III - Love Is the Pulse of the Stars',
    'Gekkou no Pierce: Yumemi to Gin no Bara no Kishidan',
    'Juuza Engi: Engetsu Sangokuden - Gaiden Youzhou Genya',
    'Mai-Otome Special: Otome no Inori',
    'Bakuretsu Hunters OVA',
    'Ontama!',
    'Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e (TV)',
    'Obake no Q-tarou',
    'Mikan-Seijin',
    'BOY&#039;s LOVE Nitro+CHiRAL',
    'Aachi wa Ssipak',
    'Xiao Yeyou',
    'Balloon (Music)',
    'Douluo Dalu',
    'Ao no Exorcist Movie Special',
    'Kore ga UFO da! Soratobu Enban',
    'Notari Matsutarou',
    'Patalliro! Stardust Keikaku',
    'Buta',
    'Soukou Kijo Iris',
    'Alice Tantei Kyoku',
    'Arakawa Under the Bridge x Bridge',
    'Shoujo☆Kageki Revue Starlight',
    'Weiß Kreuz Glühen',
    'Kino no Tabi: Nanika wo Suru Tame ni - Life Goes On.',
    'Reideen',
    'Tenchi Muyou! Ryououki 3rd Season Picture Drama',
    'Yuuto-kun ga Iku Movie',
    'Kindaichi Shounen no Jikenbo: Kuromajutsu Satsujin Jiken-hen',
    'Shin Strange+ Special',
    'Joukyou Monogatari',
    'School Days',
    'Gaist Crusher',
    'Initial D Fourth Stage',
    'Kagee Grimm Douwa',
    'Ningyohime Marina no Bouken',
    'Aru Zombie Shoujo no Sainan',
    'Hetalia Axis Powers',
    'Mugen Kouro',
    'Wind: A Breath of Heart (TV)',
    'Pochacco no Wakuwaku Birthday',
    'Mahoutsukai Tai! vs. Shamanic Princess',
    'Kitty-chan wo Sagase! Toyama-shi Stamp Rally',
    'Yousei Dick',
    'Kachikachi Yama (1940)',
    'Ultra B: Black Hole kara no Dokusaisha BB!!',
    'Biohazard 4D-Executer',
    'Brave Witches: Petersburg Daisenryaku',
    'Ginga Tetsudou 999: Glass no Clair',
    'Osiris no Tenbin: Season 2',
    'Toaru Majutsu no Index-tan II',
    'Takarajima',
    'Gundam Build Fighters: GM no Gyakushuu',
    'Urusei Yatsura Movie 2: Beautiful Dreamer',
    'Kaette Kite yoo Toyama kara',
    'Digital Juice',
    'Show By Rock!!: Plasmagica na Gogo',
    'Kuragehime: Eiyuu Retsuden☆',
    'Hikaru Genji: Paradise Ginga',
    'Ebiten: Kouritsu Ebisugawa Koukou Tenmonbu OVA',
    'Tamayura: Sotsugyou Shashin Part 3 - Akogare',
    'Saimin Jutsu Zero Special',
    'Saint Seiya: Tenkai-hen Josou - Overture',
    'One Piece Movie 1',
    'Jungle Taitei Leo: Hon-o-ji',
    'Minna no Doutoku',
    'Donguri to Yamaneko (1995)',
    'Ergo Proxy',
    'Doraemon Movie 13: Nobita to Kumo no Oukoku',
    'Tantei Opera Milky Holmes Movie: Gyakushuu no Milky Holmes',
    'Windaria',
    'Kizuna Ichigeki',
    'xxxHOLiC Shunmuki',
    'Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-hen',
    'Choujuushin Gravion Zwei',
    'Mo Dao Zu Shi',
    'Inmu Gakuen: Inmu ni Torawareta Bijin Shimai',
    'Inyouchuu The Animation',
    'Hakimono to Kasa no Monogatari',
    'Xingji Biaoche Wang',
    'Berserk: Ougon Jidai-hen I - Haou no Tamago',
    'Dragon Ball Z Movie 14: Kami to Kami',
    'Wasure-boshi',
    'Shadow Skill: Eigi',
    'Kiki to Lala no Papa to Mama ni Aitai',
    'Wanwan Sanjuushi',
    'Taiheiyou ni Kakeru Niji',
    'Konchuu Monogatari Minashigo Hutch (1989)',
    'Guin Saga',
    'Kuroshitsuji II',
    'Amai Choubatsu: Watashi wa Kanshu Senyou Pet',
    'E&#039;s Otherwise',
    'Watashi ga Toriko ni Natte Yaru',
    'Code Geass: Hangyaku no Lelouch I - Koudou',
    'Area 88',
    'Natsumi Step!',
    'Egomama',
    'Sakura Internet',
    'Rakushou! Hyper Doll',
    'Highschool of the Dead: Drifters of the Dead',
    'Juuou Mujin no Fafnir',
    'Ristorante Paradiso',
    'SOS TV Walpurgis Night Fever',
    'Dragon Quest: Dai no Daibouken (1991)',
    'Smile Precure!',
    'Katsugeki/Touken Ranbu',
    'Hunter x Hunter (2011)',
    'Lovedol: Lovely Idol OVA',
    'Non Non Biyori Repeat',
    'Yagami-kun no Katei no Jijou',
    'Natsume Yuujinchou Go',
    'Slow Step',
    'Kijutsushi x Majutsushi: Osaka Tanteibu no Jikenbo',
    'Gintama°: Umai-mono wa Atomawashi ni Suru to Yokodorisareru kara Yappari Saki ni Kue',
    'Furyou ni Hamerarete Jusei Suru Kyonyuu Okaasan The Animation',
    'Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen',
    'Pulsar',
    'Hikenai Guitar wo Hikundaze',
    'Rozen Maiden',
    'Akuma to Himegimi',
    'Super Speed',
    'Phantom: Requiem for the Phantom',
    'Futari Ecchi',
    'Kyoto Animation: Hana-hen',
    'Initial D Battle Stage',
    'Cheburashka Arere?',
    'Devil May Cry',
    'Ihatov Gensou: Kenji no Haru',
    'Manga Kotowaja Jiten',
    'Chuumon no Ooi Ryouriten (1991)',
    'Hyakka Ryouran: Samurai Girls',
    'Hanayamata',
    '3D Kanojo: Real Girl',
    'Harmony',
    'Jungle wa Itsumo Hare nochi Guu Deluxe',
    'Mai-HiME: Kuro no Mai/Saigo no Bansan',
    'Sensou no Tsukurikata',
    'Injuu Daikessen',
    'Juusen Battle Monsuno',
    'Slow Start: Web Yokoku Movie',
    'Tibet Inu Monogatari',
    'Charady no Joke na Mainichi',
    'Still',
    'Kikou Senki Dragonar',
    'Hetalia: The World Twinkle Specials',
    'Naki no Ryuu: Hiryuu no Shou (1991)',
    'W&#039;z',
    'Soul Reviver',
    'Kokekkou-san',
    'Touhou Niji Sousaku Doujin Anime: Musou Kakyou Special',
    'Gin no Saji 2nd Season',
    'Uma Musume: Pretty Derby (TV)',
    'Kokoro Toshokan: Communication Clips',
    'Kokoro Toshokan',
    'Soukyuu no Fafner: Right of Left - Single Program',
    'Armageddon',
    'The Perfect World',
    'Idol Project',
    'New Initial D Movie: Legend 3 - Mugen',
    'Seikai no Danshou: Tanjou',
    'Shingeki no Kyojin Movie 3: Kakusei no Houkou',
    'Ikoku na Retro',
    'Detective Conan Movie 11: Jolly Roger in the Deep Azure',
    'Hitoriga The Animation',
    'Phantasm',
    'Uchiage Hanabi, Shita kara Miru ka? Yoko kara Miru ka?',
    'Jiaoao de Jiangjun',
    'Oi! Ryouma',
    'An Ling Yu Shi Di Qi',
    'Appare! Momotarou no Koutsuu Anzen',
    'Sumeba Miyako no Cosmos-sou Suttoko Taisen Dokkoida',
    'Pokemon Best Wishes! Season 2: Decolora Adventure - Iris vs. Ibuki! Dragon Master e no Michi!!',
    'Ore no Imouto ga Konnani Kawaii Wake ga Nai',
    'Futari wa Precure: Splash☆Star Movie - Tick Tack Kiki Ippatsu!',
    'Houkago no Ouji-sama',
    'Iruka to Shounen',
    'Yamato Nadeshiko Shichihenge♥',
    'Shirouto Kurabu',
    'Koala Boy Kokki',
    'Shin Choujin Densetsu Urotsukidouji Mataiden',
    'Aa! Megami-sama!: Sorezore no Tsubasa',
    'Hakata Tonkotsu Ramens',
    'Monster Farm: Enbanseki no Himitsu',
    'Kono Aozora ni Yakusoku wo: Youkoso Tsugumi Ryou e',
    'Manga Revue Haru',
    'Blame! Special',
    'Shounen Santa no Daibouken!',
    'Abarenbou Rikishi!! Matsutarou',
    'Shingeki no Kyojin Picture Drama',
    'Kaze no Kokyuu: Animation ni Yoru Oufuku Shokan',
    'Usagi no Matthew',
    'Dokkiri Doctor',
    'Kuchao',
    'Katte ni Shirokuma',
    'Kizuna',
    'Ma ga Ochiru Yoru',
    'Oshiri Kajiri Mushi (TV) 4th Season',
    'Minami-ke Okaeri',
    'Itazura Tenshi Chippo-chan',
    'Fate/Extra: Last Encore - Irusterias Tendouron',
    'Usavich',
    'Jikuu Tantei Genshi-kun',
    'Hyakka Ryouran: Samurai Bride Specials',
    'Ryuu Seiki',
    'Toushin Toshi II',
    'Pikotarou no Lullaby Lullaby',
    'Saru Masamune',
    'Jungle Taitei Movie (1997)',
    'Omakase Scrappers',
    'Rio: Rainbow Gate!',
    'Romantica Clock',
    'Meiji x Kokosake & anohana Receipt Oubo Campaign',
    'Urusei Yatsura Movie 6: Itsudatte My Darling',
    'Aru Hi Inu no Kuni kara Tegami ga Kite',
    'Sono Hanabira ni Kuchizuke wo: Reo x Mai Diaries',
    'JK to Ero Giin Sensei',
    'Pikkoman no Kichikumichi: Mayonaka no Milk Party',
    'Code Geass: Hangyaku no Lelouch R2 Picture Drama',
    'Chou Seimeitai Transformers Beast Wars Metals: Convoy Daihenshin!',
    'Kaidan',
    'Gregorio',
    'Megami Tantei Vinus File',
    'Puyo Puyo: Madou Monogatari',
    'Meisou! Underworld',
    'Azure Nihon Data Center',
    'Keroro Gunsou: KeroZero Shupattsudayo! Zeninshuugou!',
    'Alps no Shoujo Heidi: Alm no Yama-hen',
    'Kono Subarashii Sekai ni Shukufuku wo! OVA',
    'Qin Shi Ming Yue: Bai Bu Fei Jian',
    'Sanrio Anime Sekai Meisaku Gekijou',
    'Tight-rope',
    'Lao Fu Zi Shui Hu Chuan',
    'Di Gi Charat: Hoshi no Tabi',
    'Soliton no Akuma',
    'Wagamama☆Fairy Mirumo de Pon!',
    'The Snack World',
    'Manichi ga Tsurai Kimochi Wakarimasu ka: Yurusenai! Net Ijime',
    'Mobile Suit Gundam: Iron-Blooded Orphans 2nd Season',
    'Nyuru Nyuru!! Kakusen-kun 2nd Season',
    'Hi no Youjin',
    'Sister Princess: Re Pure',
    'Kaijuu no Ballad',
    'Ulysses 31 Pilot',
    'Seishoujo Kantai Virgin Fleet',
    'Chicchana Yukitsukai Sugar',
    'Mai-Otome Zwei',
    'Master Keaton OVA',
    'Konchuu Monogatari Tentoumu Chu! to Mitsubachi Hatsu Chu!',
    'Matsubara-kun: Mackie E no Ouen Message',
    'Hello Kitty no Nemureru Mori no Bijo',
    'Layton Kyouju to Eien no Utahime',
    'Precure All Stars DX the Dance Live♥: Miracle Dance Stage e Youkoso',
    'Tobidase! Machine Hiryuu',
    'Shounan Bakusouzoku',
    'Sore Ike! Anpanman: Yumeneko no Kuni no Nyanii',
    'Toki no Tabibito: Time Stranger',
    '.hack//Versus: The Thanatos Report',
    'Brigadoon: Marin to Melan',
    'Spocon!',
    'Inazuma Eleven Go: TCG CM NG-shuu',
    'Corpse Party: Missing Footage',
    'One Piece 3D: Mugiwara Chase',
    'Blossom',
    'Yasai no Yousei: N.Y.Salad',
    'Kojin Toshi',
    'Kitakaze no Kureta Table-kake',
    'Daikyouryuu Jidai',
    'Ramayana: The Legend of Prince Rama',
    'Himitsukessha Taka no Tsume NEO',
    'Paboo & Mojies',
    'Pokemon Advanced Generation: Rekkuu no Houmonsha Deoxys',
    'gdgd Fairies 2',
    'Around',
    'Hikari no Densetsu',
    'Tsuki to Azarashi',
    'Haiyore! Nyaruko-san F',
    'Kemeko Deluxe!',
    'Chou Deneiban SD Gundam Sangokuden Brave Battle Warriors',
    'The Everlasting Guilty Crown',
    'Mahoutsukai Precure! Movie: Kiseki no Henshin! Cure Mofurun!',
    'Peeping Life: The Perfect Extension',
    'Kouchuu Ouja Mushiking: Mori no Tami no Densetsu',
    'Yomigaeru Sora: Rescue Wings',
    'Fr/day Night',
    'Awate Tokoya',
    'Tamayura: Hitotose - Attakai Kaze no Omoide, Nanode',
    'Shin Reyon Densetsu: Mou Hitori no Flair',
    'Karneval (TV)',
    'Ojamajo Doremi Sharp Movie',
    'Military!',
    'MTV Japan Station ID',
    'Gakuen 3',
    'Taka no Tsume 7: Joou Heika no Jobuubu',
    'Cardfight!! Vanguard: Link Joker-hen',
    'Nonki na Tou-san Ryuuguu Mairi',
    'Detective Conan Movie 02: The Fourteenth Target',
    'DRAMAtical Murder OVA: Data_xx_Transitory',
    'Tasogare Otome x Amnesia',
    'Yuuki Yuuna wa Yuushabu Shozoku 3',
    'Teekyuu 9',
    'Kiekaketa Monogataritachi no Tame ni',
    'Hidamari Sketch x 365 Recap',
    'Gokusen',
    'Kemonozume',
    'Ikoku Meiro no Croisée Picture Drama',
    'Mahou Shoujo Madoka★Magica Movie 3: Hangyaku no Monogatari - Magica Quartet x Nisioisin',
    'Yasashii Kinyoubi',
    'Ashita Genki ni Nare!: Hanbun no Satsumaimo',
    'Ginga Tetsudou Monogatari: Eien e no Bunkiten',
    'Bleach Movie 1: Memories of Nobody',
    'Oshare Kozou wa Hanamaru',
    'Soap no Moko-chan',
    'Shimanchu MiRiKa',
    'Fuuka',
    'Ame no Ten Ten',
    'Level E',
    'Highschool Aurabuster: Hikari no Mezame',
    'Imouto to Sono Yuujin ga Ero Sugite Ore no Kokan ga Yabai',
    'Baymax',
    'Aoi Hitomi no Onnanoko no Ohanashi',
    'Cynical Hysterie Hour: Trip Coaster',
    'Karo to Piyobupt: Sandwich',
    'Reiju Gakuen',
    'Hi☆sCoool! SeHa Girls Special',
    'Funassyi to Yukaina Kyoudai',
    'Baby Baachan',
    'Koikishi Purely☆Kiss The Animation: Special Edition',
    'K: Seven Stories Movie 1 - R:B - Blaze',
    'Ginga Eiyuu Densetsu: Arata Naru Tatakai no Overture',
    'Mobile Suit Gundam Unicorn',
    'Tsuma no Haha Sayuri',
    'Ao Oni The Animation (Movie)',
    'Ojarumaru Yakusoku no Natsu Ojaru to Semira Movie',
    'Shunga',
    'Yami Shibai',
    'Bloodivores',
    'Hunter x Hunter: Greed Island Final',
    'Kamisama no Inai Nichiyoubi',
    'Eureka Seven AO',
    'Mad★Bull 34',
    'Daikuu Maryuu Gaiking',
    'Kikansha Yaemon',
    'Detective Conan Movie 07: Crossroad in the Ancient Capital',
    'Daisougen to Hakuba',
    'Muteki Robo Trider G7',
    '"Parade" de Satie',
    'Major S6',
    'Decadence: Remix',
    'Nana',
    'Black Jack: Sora kara Kita Kodomo',
    'Luck & Logic',
    'Columbos',
    'Black Shout',
    'Sakura Taisen: Sumire',
    'PES: Peace Eco Smile',
    'Burn Up Excess',
    'Lupin III: Nusumareta Lupin',
    'Neko no Robu',
    'Portrait',
    'Kori no Koe',
    'Henkei Sakuhin Dai 2-ban',
    'Okusama ga Seitokaichou! OVA: Okusama Gekijou',
    'Exper Zenon',
    'Cluster Edge Specials',
    'Tottoko Hamtarou OVA 4: Hamuchanzu no Mezase! Hamuhamu Kin Medal - Hashire! Hashire! Daisakusen',
    'Seikai no Senki Special',
    'Mou Hitotsu no Nijiiro Toshi',
    'HeatGuy J Special',
    'Junk Boy',
    'Inakappe Taishou',
    'Maze☆Bakunetsu Jikuu (TV)',
    'Shukufuku no Campanella Specials',
    'Tantei Opera Milky Holmes: Summer Special',
    'MapleStory Special',
    'Romeo no Aoi Sora',
    'Saimin☆Gakuen',
    'Crusher Joe',
    'Saiki Kusuo no Ψ-nan (TV)',
    'Crayon Shin-chan Movie 22: Gachinko! Gyakushuu no Robo To-chan',
    'Nar Doma Special',
    'Otogi Story Tenshi no Shippo Specials',
    'Owari no Seraph: Nagoya Kessen-hen',
    'Pretty Rhythm: Rainbow Live',
    'Ikedaya Soudou',
    'Kara no Kyoukai 8: Shuushou',
    'Golgo 13: Queen Bee',
    'Seitokai no Ichizon',
    'Saiki Kusuo no Ψ-nan (TV) 2',
    'Pokemon Diamond & Pearl',
    'Sora no Otoshimono: Forte',
    'Minihams no Kekkon Song',
    'Pokemon Diamond & Pearl: Clip Show',
    'Origami Warriors',
    'Dennou Coil',
    'Haunted Junction',
    'Meikyoku to Dai Sakkyokka Monogatari',
    'Tough Guy!',
    'Akina to Onsen de H Shiyo!',
    'Auction: Bijo Dorei',
    'Ujusonyeon Kaesi',
    'Agigongryong Doolie (Movie)',
    'Boku wa Konomama Kaeranai',
    'xxxHOLiC Kei',
    'Princess Nine: Kisaragi Joshikou Yakyuubu',
    'Sekai de Ichiban Tsuyoku Naritai!',
    'Versailles no Bara to Onna-tachi',
    'Hong Xing Xiao Yong Shi',
    'FunaQ: Funassyi to Soutai-kun',
    'Yakumo Tatsu',
    'Bouken Korobokkuru',
    'Hakken Taiken Daisuki! Shimajirou',
    'Ghost in the Shell: Stand Alone Complex 2nd GIG',
    'Nineko Gelée',
    'Shin Koihime†Musou',
    'Strike the Blood II',
    'Gamba to Kawauso no Bouken',
    'Tamayura: Sotsugyou Shashin Part 2 - Hibiki',
    'Keroro',
    'Doraemon: Doraemon Comes Back (Movie)',
    'Backkom Meogeujan Yeohaeng',
    'Jeremy no Ki',
    'Lord of Vermilion IV',
    'Majin Tantei Nougami Neuro',
    'Garakuta-doori no Stain',
    '3-Nen C-Gumi 14-Ban Kubozono Chiyoko no Nyuukaku',
    'Kobato.',
    'Choujuu Densetsu Gestalt',
    'Taiyou no Ouji: Horus no Daibouken',
    'Grimm Masterpiece Theater II',
    'Tekkon Kinkreet Pilot',
    'One Room',
    'Shouwa Ahozoushi Akanuke Ichiban!',
    'Inazuma Eleven Go: Chrono Stone',
    'Blend',
    'Makyou Densetsu Acrobunch',
    'Megumi to Taiyou: Kajuu Gummi Tweet Love Story',
    'Tentai Senshi Sunred 2nd Season',
    'Kakyuusei 2: Hitomi no Naka no Shoujo-tachi',
    'Chibi Maruko-chan (1995)',
    'Mukashi Mukashi Momotarou',
    'Animation!',
    'Kuroko no Basket 2nd Season',
    'Mujin Wakusei Survive',
    'Mei to Koneko Bus',
    'Dash! Kappei',
    'Yume no Ukiyo ni Saitemina',
    'Kidou Senkan Nadesico: The Prince of Darkness',
    'Shiroki Tenshi-tachi no Rondo',
    'Wana: Hakudaku Mamire no Houkago',
    'Makai Ouji: Devils and Realist',
    'Maburaho',
    'Tales of the Rays',
    'Otome Hime',
    'Peach Command Shin Momotarou Densetsu',
    'Hanada Shounen-shi',
    'Cyborg 009: Call of Justice 3',
    'Mouryou no Hako',
    'Saishuu Chikan Densha Next',
    'Sin: Nanatsu no Taizai Zange-roku',
    'Furusato Japan',
    'Interlude',
    'Poputepipikku',
    'Doraemon Movie 27: Nobita no Shin Makai Daibouken - 7-nin no Mahoutsukai',
    'Ponta to Ensoku',
    'Yakusoku (ONA)',
    'Spo-chan Taiketsu: Youkai Daikessen',
    'Odoriko Clinoppe',
    'The iDOLM@STER',
    'Nemurenu Yoru no Chiisana Ohanashi',
    'Passion',
    'Mahoutsukai no Yome Recap',
    'Toji no Miko',
    'Sword Art Online Alternative: Gun Gale Online - Refrain',
    'Angel Heart',
    'Princess Rouge',
    'Usavich II',
    'Kirameki☆Project',
    'Junjou Shoujo Et Cetera',
    'Himitsukessha Taka no Tsume The Movie 1: Soutou wa Nido Shinu',
    'Gakkou no Kowai Uwasa: Hanako-san ga Kita!!',
    'Otome Dori',
    'Ghost in the Shell: The New Movie Virtual Reality Diver',
    'Sora Iro no Tane',
    'Ijime Stop! Kintarou Kokoro Chikaramochi',
    'Koutetsu no Majo Annerose',
    'Moving Colors',
    'Ore no Sora Keiji-hen',
    'Ore ga Ojousama Gakkou ni "Shomin Sample" Toshite Gets♥Sareta Ken Specials',
    'Challenge Ichinensei de Kakkoii Ichinensei ni Henshin!',
    'PriPri Chii-chan!!',
    'Sekai Meisaku Douwa',
    'Kämpfer Picture Drama',
    'Mouretsu Pirates',
    'Kai Doh Maru',
    'Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen',
    'Uchuu Neko: Mardock no Bouken',
    'Channel 5.5 3rd Season',
    'Perman (1983) Specials',
    'Kamiusagi Rope Movie Episode 0',
    'Go! Princess Precure',
    'Detective Conan: City Exploration! Get the Animal Mark!',
    'Samurai 7',
    'Bleach Colorful!: Gotei Juusan Yatai Daisakusen!',
    'Tenchi Muyou! Ryououki 3rd Season: Tenchi Seirou naredo Namitakashi?',
    'D-Frag!',
    'Hal no Fue',
    'Divergence Eve 2: Misaki Chronicles',
    'Naccio to Pomm',
    'Canary',
    'Anime Sanjuushi: Aramis no Bouken',
    'Go! Go! Kadendanshi',
    'Cosmic Break',
    'Bloody Bunny',
    'Ultraman Kids: M7.8 Sei no Yukai na Nakama',
    'Strike Witches: Operation Victory Arrow',
    'Dantalian no Shoka: Ibarahime',
    'Aku no Hana',
    'Tough Boy',
    'Mahou Shoujo wa Kiss Shite Kawaru',
    'Soukan Rensa',
    'Kyuuketsuki',
    'Happy Jozy',
    'Haikyuu!! Second Season',
    '100-man-nen Chikyuu no Tabi: Bander Book',
    'Pankis! 2-jigen',
    'Toyoichi',
    'Beatless Intermission',
    'Aware! Meisaku-kun: Meiji Saite Oishii Mozzarella',
    'Liz to Aoi Tori',
    'Pokemon Diamond & Pearl Specials',
    'Bucket de Gohan',
    'Sister Princess',
    'Nodoka Mori no Doubutsu Daisakusen',
    'Manga Hana no Kakarichou',
    'Break-Age',
    'Kuroi Kikori to Shiroi Kikori',
    'Vampire Knight',
    'Ganbare Goemon: Jigen Jou no Akumu',
    'Working&#039;!! Announcement Specials',
    'Daisougen no Chiisana Tenshi: Bush Baby',
    'Penguin&#039;s Memory: Shiawase Monogatari',
    'Harukanaru Toki no Naka de 3: Kurenai no Tsuki',
    'Pokemon: Pikachu no Fushigi na Fushigi na Daibouken',
    'Bakusou Kyoudai Let&#039;s & Go Special',
    'Naruto SD: Rock Lee no Seishun Full-Power Ninden',
    'Yuusha ni Narenakatta Ore wa Shibushibu Shuushoku wo Ketsui Shimashita.',
    'Tamashichi!',
    'Jingi',
    'Slayers Evolution-R',
    'Oh! Super Milk-chan',
    'Aoki Hagane no Arpeggio: Ars Nova Cadenza',
    'Sexy Commando Gaiden: Sugoiyo!! Masaru-san Specials',
    'Yakusoku no Neverland',
    'Saint Seiya: Shinku no Shounen Densetsu',
    'Ninpuu Kamui Gaiden',
    'Xiang Qi Wang',
    'Aa! Megami-sama! (TV)',
    'Hatara Kids Mai Ham Gumi',
    'Hungry Heart: Wild Striker',
    'Itadaki! Seieki♥ Special',
    'Fight Ippatsu! Juuden-chan!! Specials',
    'Quantum Leap',
    'Rescue YoYo',
    'Zombie Clay Animation: I&#039;m Stuck!!',
    'And And',
    'Konigiri-kun',
    'Shin Ruri-iro no Yuki',
    'Mitsuboshi Colors',
    'Lupin III: Dead or Alive',
    'Phi Brain: Kami no Puzzle',
    'Kaze no Stigma',
    'The Samurai',
    'Butlers: Chitose Momotose Monogatari',
    'Tonari no Totoro',
    'Mechano: Scientific Attack Force',
    'Q Transformers: Saranaru Ninki Mono e no Michi',
    'Tonari no 801-chan R',
    'Platonic Chain',
    'Gegege no Kitarou (2018)',
    'Rocket Girls',
    'Futakoi',
    'Urawa no Usagi-chan Special',
    'Donten ni Warau Gaiden: Shukumei, Soutou no Fuuma',
    'Shogi Hour',
    'Onegai☆Teacher: Reminiscence Disc',
    'Houkago: Nureta Seifuku',
    'Ikkitousen: Great Guardians',
    'Houkago Nyannyan',
    'Nyani ga Nyandaa Nyandaa Kamen',
    'Kamisama Minarai: Himitsu no Cocotama Movie - Kiseki wo Okose♪ Tepple to Dokidoki Cocotama-kai',
    'Money Wars: Nerawareta Waterfront Keikaku',
    'Train Heroes Movie',
    'Shonan Junai Gumi!',
    'Hachimitsu to Clover II',
    'Wooser no Sono Higurashi: Ken to Pants to Wooser to',
    'Pure Mail',
    'Seitokai no Ichizon Lv.2: Watasu Seitokai',
    'Okawari-Boy Starzan-S',
    'Himesama Goyoujin',
    'Hundred',
    'Ranma ½: Kessen Tougenkyou! Hanayome wo Torimodose!',
    'Kusakeiba',
    'Hatsumei Boy Kanipan',
    'Nanatsu no Taizai',
    'School Rumble',
    'Dragon Ball Z',
    'Digimon Frontier: Ornismon Fukkatsu!!',
    'Great Mazinger tai Getter Robo',
    'So Ra No Wo To',
    'Kimi ni Todoke 2nd Season: Kataomoi',
    'Marude Sekai',
    'H. P. Lovecraft&#039;s The Dunwich Horror and Other Stories',
    'Ghost in the Shell: Arise - Logicoma Specials',
    'Kanashiki Mongoose',
    'Ankoku Cat VS',
    'Genei Toushi Bastof Lemon',
    'Hate You',
    'Futari Ecchi (2014)',
    'K: Seven Stories Movie 2 - Side:Blue - Tenrou no Gotoku',
    'Ladies versus Butlers! Specials',
    'Ansatsu Kyoushitsu',
    'Boku wa Tomodachi ga Sukunai',
    'Macross Fufonfia',
    'Ranma ½: Nettou Uta Gassen',
    'Forsaken',
    'Kara no Shoujo',
    'Princess Lover! OVA',
    'Baki',
    'Kikou Kai Galient',
    'Sugata Sanshirou',
    'Ikkyuu-san: Ooabare Yancha-hime',
    'Kimitachi wa Dou Ikiru ka',
    'Tairiki Tarou no Mucha Shuugyou',
    'Halfway',
    'Musaigen no Phantom World: Limitless Phantom World',
    'Sword Art Online: Alicization',
    'Go-hiki no Kozaru-tachi',
    'Inshitsu Otaku ni Ikareru Kanojo',
    'Kunoichi Bakumatsu Kitan',
    'Buddy Complex',
    'Durarara!!x2 Shou: Watashi no Kokoro wa Nabe Moyou',
    'Arete Hime',
    'Uchuu Kaizoku Sara',
    'Unicorn no Kyupi',
    'Mouretsu Pirates: Abyss of Hyperspace',
    'Pacusi',
    'Kagerouka-kun',
    'Kanojo wa Zombie',
    'Kizumonogatari I: Tekketsu-hen',
    'Anyamal Tantei Kiruminzoo',
    'Oyayubi-hime',
    'Persona 2: Another Self',
    'Pale Cocoon',
    'Toriko Hime: Hakudaku Mamire no Reijou',
    'Narara Wondeogongju',
    'Future GPX Cyber Formula Graffiti',
    'Captain',
    'Ousama to Nightingale',
    'Bokura ga Ita',
    'Choujuu Kishin Dancougar',
    'Sore Ike! Anpanman: Kaiketsu Naganegiman to Yakisobapanman',
    'Aoi Meno Ningyou Monogatari',
    'Star Driver: Kagayaki no Takuto',
    'Sore Ike! Anpanman: Tsukiko to Shiratama - Tokimeki Dancing',
    'Chou Tokkyuu Hikarian',
    'Kakuchou Shoujo-kei Trinary: Ex.MV',
    'Chousoku Henkei Gyrozetter',
    'Hissatsu Chikan Nin',
    'Bikkuriman',
    'Heisei Tensai Bakabon',
    'Fate/kaleid liner Prisma☆Illya 2wei Herz!',
    'Momotarou no Koutsuu Anzen Kyoushitsu',
    'Waku Waku Koma-chan',
    'Kudan',
    'Mobile Suit Gundam-san: Hiyoko day&#039;s Ichisuisei Hiyoko to Fushigi na Ofuda',
    'Kiko-chan Smile',
    'Strike the Blood III',
    'Taiho Shichau zo: Full Throttle Special',
    'Tousan no Tsukutta Uta',
    'Micro Teukgongdae Diatron 5',
    'Persona 3 the Movie 2: Midsummer Knight&#039;s Dream',
    'Macross',
    'Bary-san no Shokoku Manyuuki',
    'Music Up',
    'Mobile Suit Gundam Wing',
    'Shizuku',
    'Daisuki! Nendomama',
    'Kuttsukiboshi',
    'SoniAni: Super Sonico The Animation',
    'Shining Hearts: Shiawase no Pan - Kokoro ga Todoita Picture Drama',
    'Youkai Ninpouchou Jiraiya!',
    'Digimon Adventure tri. 1: Saikai',
    'Flutter of Birds: Tori-tachi no Habataki',
    'Blue Seed',
    'Kaumori',
    'Fate/stay night: Unlimited Blade Works - Prologue',
    'Xia Lan',
    'Stitch!: Zutto Saikou no Tomodachi Special',
    'Hidamari Sketch x ☆☆☆',
    'Sore Ike! Anpanman: Kyouryuu Nosshii no Daibouken',
    'Touch 3: Kimi ga Toorisugita Ato ni - Don&#039;t Pass Me By',
    'Mother: Saigo no Shoujo Eve',
    'Doraemon: Obaachan no Omoide',
    'Ahiru no Otegara',
    'Haikara-san ga Tooru Movie 1: Benio, Hana no 17-sai',
    'Mokkai Shiyo?',
    'Seraphim Call',
    'Issho ni Training: Training with Hinako',
    'Boku wa Robot-goshi no Kimi ni Koi wo Suru',
    'Dead World',
    'YU-NO',
    'Sukitte Ii na yo.',
    'Naruto Movie 2: Dai Gekitotsu! Maboroshi no Chiteiiseki Dattebayo!',
    'Atama Yama',
    'Sore Ike! Anpanman: Anpanman to Oyakusoku',
    'Mitsu x Mitsu Drops',
    'Kimi no Na wa.',
    'Naisho no Hanashi',
    'Tetsuwan Atom (1980)',
    'Meoteoldosawa Ttomae',
    'Kacchikenee!',
    'Kamiwaza Wanda',
    'Wakaba*Girl',
    'Kamisama no Inai Nichiyoubi: Kioku',
    'Message Song',
    'KO Seiki Beast Sanjuushi',
    'Private Emotion',
    'Pastel Kazoku',
    'Tenchi Muyou! Ryououki',
    'Kakumeiki Valvrave 2nd Season',
    'Garo: Uzusumizakura',
    'Mister Ajikko Special',
    'Kuma no Minakuro to Kouhei Jiisan',
    'Hoshikuzu Paradise',
    'Nakano Harada Kekkon Kyousoukyoku',
    'Double-J',
    'Mahou no Star Magical Emi',
    'Doraemon: Nobita to Mirai Note',
    'Puchimas!: Petit iDOLM@STER',
    'Kuiba II: Dazhan Yuan Yang Jie',
    'Shoujo-tachi no Sadism The Animation',
    'Love Like Aliens',
    'Neon Genesis Evangelion: Death & Rebirth',
    'Detective Conan Movie 05: Countdown to Heaven',
    'Harukanaru Toki no Naka de: Hachiyou Shou',
    'Ravex in Tezuka World',
    'Poka Poka Mori no Rascal',
    'Gowapper 5 Gordam',
    'Daiakuji: The Xena Buster Specials',
    'Kaiketsu Jouki Tanteidan',
    'Granblue Fantasy',
    '.hack//G.U. Returner',
    'Mazinger Z',
    'Appleseed XIII Remix Movie 2: Yogen',
    'Manga Edo Erobanashi',
    'Genius Party Beyond',
    'Hime-chan no Ribbon',
    'Soul Eater: Late Night Show',
    'Deimos no Hanayome: Ran no Kumikyoku',
    'Shingeki no Kyotou',
    'Major 2nd (TV)',
    'True Tears',
    'Yadamon',
    'Kimi no Na wo Yobeba',
    'Imakara Atashi......',
    'Esper Mami Special: My Angel Mami-chan',
    'Arcana Famiglia: Capriccio - stile Arcana Famiglia',
    'Yuusei Kamen',
    'Cross Game',
    'Megami Tengoku',
    'Tennis no Ouji-sama: Zenkoku Taikai-hen - Semifinal',
    '47 Todoufuken Specials',
    'Eyeshield 21: Jump Festa 2005 Special',
    'Neko Ramen: Ore no Shouyu Aji',
    'Ninja Senshi Tobikage',
    'Dakaretai Onna',
    'Rurouni Kenshin Special',
    'Crayon Shin-chan Movie 26: Bakumori! Kung Fu Boys - Ramen Tairan',
    'Slime Boukenki: Umi da, Yeah!',
    'Di Gi Charat',
    'Dororon Enma-kun Meeramera',
    'Kaze wo Mita Shounen',
    'Suzumiya Haruhi no Shoushitsu',
    'Tales of Symphonia The Animation: Sylvarant-hen',
    'La Seine no Hoshi',
    'Kintarou',
    'Fushigi na Koala Blinky',
    'Love Hina Final Selection',
    'Brave Story',
    'Tezuka Osamu no Buddha: Owarinaki Tabi',
    'Kanon',
    'Sarusuberi: Miss Hokusai',
    'Higurashi no Naku Koro ni Kira',
    'Magikano',
    'Kita e: Pure Session',
    'Tatakau Shisho: The Book of Bantorra',
    'Gou-chan. Moko to Chinjuu no Mori no Nakama-tachi',
    'Taimanin Asagi Special',
    'Kaizoku Ouji',
    'Karugamo Oyako no Hi no Youjin',
    'Naruto: Shippuuden Movie 2 - Kizuna',
    'Burning Village',
    'Many Things SD Gundam',
    'Youkai Watch: Best 10',
    'Warau Salesman Dai SP-banashi',
    'Yoligongju Loopy',
    'Hermes: Ai wa Kaze no Gotoku',
    '44-hiki no Neko',
    'Hokori Inu no Hanashi',
    'Majo no Takkyuubin',
    'Machi Ichiban no Kechinbou',
    'Saiyuuki Reload',
    'Memories',
    'Dragon Ball: Episode of Bardock',
    'D.C.II: Da Capo II',
    'Gintama: Yorinuki Gintama-san on Theater 2D',
    'Kakusansei Million Arthur',
    'Private Eye Dol',
    'Anata wo Zutto Aishiteru',
    'Ginga e Kickoff!!',
    'Historical',
    'Shouwa Genroku Rakugo Shinjuu',
    'Hane',
    'Hachimitsu to Clover',
    'Mirai Shounen Conan',
    'Moonrakers',
    'Uta Kata Special',
    'Chikotan',
    'Chain Chronicle: Haecceitas no Hikari',
    'Setsuzoku Muyou',
    'Dragoon',
    'Doraemon: Nobita&#039;s the Night Before a Wedding',
    'Fashion',
    'Sakura Taisen: New York',
    'Zekkyou Gakkyuu: Tensei',
    'Bari Bari Densetsu',
    'Mama wa Shougaku 4 Nensei',
    'Yu☆Gi☆Oh! Arc-V',
    'Rean no Tsubasa',
    'Gakuen Shimai',
    'Kokoro ga Sakebitagatterunda. x Sony Hi-Res "Walkman" and Headphone',
    'Transformers the Movie',
    'SNS Police',
    'Masamune-kun no Revenge',
    'Shakotan★Boogie',
    'Kitte no Gensou',
    'Jokei Kazoku: Inbou',
    'Henkei Sakuhin Dai 1-ban',
    'Hayate no Gotoku! Can&#039;t Take My Eyes Off You',
    'Bakuten Shoot Beyblade 2002',
    'Potecco Babies',
    'Tobacco wa Dasai',
    'Issunboushi: Chibisuke Monogatari',
    'Mabeob Chunjamun: Daemawangui Buhwaleul Magala',
    'Lolita Anime',
    'Ace wo Nerae! (1979)',
    'Moyashimon: Kin Gekijou Deluxe',
    'Spicy Swingy Style',
    'Souten no Ken Re:Genesis',
    'The Primitives: Bongo and Grunge',
    'Uchuu Senkan Yamato',
    'Shinryaku!! Ika Musume',
    'Fei Ren Zai',
    'I My Me! Strawberry Eggs',
    'Ankoku Shinwa',
    'Date A Live',
    'Bomberman Jetters',
    'Kappa no Kaikata',
    'Sennen Joyuu',
    'Aoki Uru',
    'Fake Doll',
    'Inbaku Gakuen',
    'Tanita Shokudou',
    'Candy Boy: Nonchalant Talk of the Certain Twin Sisters in Daily Life',
    'Dagram vs. Round-Facer',
    'Hi no Tori',
    'Noobow: Na Kokoro',
    'Kochira Katsushikaku Kameari Kouenmae Hashutsujo: The Final - Ryoutsu Kakichi Saigo no Hi',
    'Issho ni H Shiyo',
    'Pokemon',
    'Umi no Yami, Tsuki no Kage',
    'Matou Kitan Zankan!',
    'Genshiken Nidaime',
    'Baka to Test to Shoukanjuu',
    'Handa-kun',
    'Growlanser IV: Wayfarer of the Time',
    'Hello Kitty no Shirayuki-hime',
    'Vandread',
    'Tetsu no Ko Kanahiru',
    'Heppoko Jikken Animation Excel♥Saga',
    'Rockman.EXE Movie: Hikari to Yami no Program',
    'Kuro Ai: Hitoyozumakan Inkou Rannyuuroku',
    'Osomatsu-san: Ouma de Kobanashi',
    'Dear Brave',
    'Last Exile: Doyou no Asa',
    'Overlord: Ple Ple Pleiades Theatrical Version',
    'Chinkoroheibei Tamatebako',
    'Mameshiba',
    'Amaenaide yo!! Katsu!!: Damasarenaide yo!!',
    'Baguda-jou no Touzoku',
    'Nuki Doki! Tenshi to Akuma no Sakusei Battle',
    'Happy Day',
    'Shin Saishuu Chikan Densha',
    'Metronome',
    'Nice to See You',
    'Rurouni Kenshin: Meiji Kenkaku Romantan - Ishinshishi e no Chinkonka',
    'Gin no Guardian',
    'Kenka no Ato wa',
    'Isshuukan Friends. Specials',
    'Daitoshokan no Hitsujikai Picture Drama',
    'Saber Marionette R',
    'One and Three Four',
    'Bouningen Weekend',
    'Kemono no Souja Erin Recap',
    'Sakurada Reset',
    'Koitabi: True Tours Nanto',
    'Clock',
    'Shinkon Gattai Godannar!! 2nd Season',
    'Maboroshi Mabo-chan',
    'Momoiro Milk',
    'Robby to Kerobby',
    'Shi Wan Ge Leng Xiaohua (Movie)',
    'Lupin III: Bye Bye Liberty - Kiki Ippatsu!',
    'Tokyo Ghoul',
    'Coyote Ragtime Show',
    'Shakugan no Shana: Friagne to Marianne no Naze Nani Shana! Nandemo Shitsumonbako!',
    'Shakugan no Shana: Naze Nani Shana! Nandemo Shitsumonbako! Special',
    'Interior',
    'Nichijou: Original Jikai Yokoku',
    'White Fantasy',
    'Sword Art Online Alternative: Gun Gale Online',
    'Kidou Keisatsu Patlabor 2 the Movie',
    'Shin Tennis no Ouji-sama',
    'Wake Up, Girl Zoo!',
    'Brilliant Better',
    'Red Garden',
    'Arad Senki: Slap Up Party',
    'Kurohime: Shikkoku no Yakata',
    'Tsuugakuro',
    'Nanocore: NG Scenes - Nano&#039;s Daily Life',
    'Gintama°',
    'Precure All Stars Movie New Stage 3: Eien no Tomodachi',
    'Blocker Gundan IV Machine Blaster',
    'Chao Zhi Neng Zu Qiu',
    'Uchuu Bouei-tai Taabou no Shinkirou Hoshi wo Sukue!',
    'Patapata Hikousen no Bouken',
    'King of Fighters: Another Day',
    'Yubi wo Nusunda Onna',
    'Jangdokdae',
    'Ouritsu Uchuugun: Honneamise no Tsubasa',
    '1000-nen Joou: Queen Millennia',
    'Hakuouki Hekketsuroku Episode 0',
    'Kyonyuu Reijou MC Gakuen',
    'Yuu☆Yuu☆Hakusho: Eizou Hakusho',
    'Sekaiichi Hatsukoi: Valentine-hen',
    'Sekai Meisaku Douwa: Wow! Maerchen Oukoku',
    'Aho Girl',
    'Hoshi wo Katta Hi',
    'Chain Chronicle: Haecceitas no Hikari Part 2',
    'Mobile Suit Gundam Wing: Endless Waltz',
    'Bakukyuu Renpatsu! Super B-Daman Specials',
    'Hakumei to Mikochi',
    'YAT Anshin! Uchuu Ryokou',
    'Yasai no Yousei: Quiz Gekijou',
    'Yama no Susume: Second Season Specials',
    'Digimon Adventure 3D: Digimon Grand Prix!',
    'Usakame',
    'Battle Spirits: Ryuuko no Ken',
    'Pokemon: Pikachu no Fuyuyasumi',
    'Tetsujin 28-gou (1980)',
    'Code Geass: Hangyaku no Lelouch III - Oudou',
    'Spider Riders: Oracle no Yuusha-tachi',
    'To Be Heroine',
    'Waanabi.jk',
    'Yasashii Fue, Tori, Ishi',
    'Peace Hame!',
    'Tenbatsu Angel Rabbie☆',
    'Rose O&#039;Neill Kewpie',
    'Wonder Gravity: Pino To Juuryoku Tsukai',
    'Bamboo Blade: Fanfu-Fufe-Fo',
    'Girls Bravo: First Season',
    'Hana wa Saku: Touhoku ni Saku',
    'Genki!! Ekoda-chan',
    'Ohayou! Kokekkou-san',
    'Gantz:O',
    'Yurumates',
    'Granblue Fantasy The Animation 2',
    'Melody',
    'Aki no Puzzle',
    'Guru Guru Town Hanamaru-kun',
    'Getsuyoubi no Tawawa Specials',
    'Yot-chan no Fushigina Crayon',
    'Tanoshii Muumin Ikka Bouken Nikki',
    'Kurenai no Buta',
    'Amagami SS+ Plus Specials',
    '3-gatsu no Lion 2nd Season',
    'Arara',
    'Samurai Flamenco',
    'Mekakucity Reload',
    'Digimon Frontier',
    'Nagareboshi Lens Specials',
    'Soratobu Penguin',
    'Red Garden: Dead Girls',
    'Kimezou no Kimarimonku Ja Kimaranee. Featuring Sabu-Otoko',
    'Momotarou Densetsu',
    'Dragon Ball GT: Gokuu Gaiden! Yuuki no Akashi wa Suushinchuu',
    'Kakyuusei (TV)',
    'Brothers Conflict',
    'Magi: Sinbad no Bouken (TV)',
    'Otome wa Boku ni Koishiteru',
    'Vampire Hunter D',
    'Mononoke',
    'Danchigai Special',
    'True Blue',
    'Bishoujo Senshi Sailor Moon S: Kaguya Hime no Koibito',
    'Tonari no Seki-kun',
    'Natsu e no Tobira',
    'Hyakka Ryouran: Samurai Girls Specials',
    'Peeping Life: Shinkon-chan Kansai ni Irasshai',
    'Rudolf to Ippaiattena x Godzilla x Toho Cinemas Moving Logo Eizou',
    'Mahoraba: Heartful days',
    'Wonder-kun no Hatsu Yume Uchuu Ryokou',
    'Ai no Kiseki: Doctor Norman Monogatari',
    'Silk Road Shounen Yuuto',
    'Mitsubachi Maya no Bouken',
    'Yawaraka Atom',
    'Okubyou na Venus',
    'Garo: Vanishing Line Recap',
    'Ao no Strada',
    'Etotama',
    'Funassyi no Funafunafuna Biyori',
    'San Ge Heshang',
    'Green Saver',
    'Wata no Kuni Hoshi Pilot',
    'Boku no Imouto wa "Osaka Okan"',
    'Jewelpet Magical Change',
    'AWOL',
    'Bishoujo Yuugi Unit Crane Game Girls Galaxy',
    'Donten ni Warau',
    'Serial Experiments Lain',
    'Tezuka Osamu ga Kieta?! 20 Seiki Saigo no Kaijiken',
    'Deva Zan',
    'Jinrui wa Suitai Shimashita Specials',
    'Adachi-ga Hara',
    'Tiger & Bunny Movie 1: The Beginning',
    'Monster Hunter Stories: Ride On',
    'Gatchaman',
    'Machine Hayabusa',
    'Masuda Kousuke Gekijou Gag Manga Biyori +',
    'Sore Ike! Anpanman: Sing! Dance! Everybody&#039;s Christmas',
    'Kill la Kill',
    'Boo Boo Boy',
    'Key the Metal Idol',
    'Yuru Camp△ Specials',
    'Shirotan: Shirotan ga Ippai!',
    'Yami no Teio: Kyuuketsuki Dracula',
    'Mushrambo (2008)',
    'Ahiru Rikusentai',
    'Detective Conan Movie 01: The Timed Skyscraper',
    'Ganbare Goemon',
    'Aki-Sora',
    'Kumo no Gakkou',
    'Star Ocean: Anamnesis',
    'Get Ride! AMDriver',
    'Tsubasa Chronicle',
    'Maro no Kanja wa Gatenkei',
    'Sora yori mo Tooi Basho',
    'Oira no Yakyuu',
    'Mako-chan no Koutsuu Anzen',
    'Try Z',
    'Romeo no Aoi Sora Specials',
    'Itoshi no Betty Mamonogatari',
    'Dragon Fist',
    'World Fool News (TV)',
    'Moom',
    'Sense Honma ni Honma',
    'Love♥Love?',
    'Evangelion: 2.0 You Can (Not) Advance',
    'Ginga Eiyuu Densetsu Gaiden (1999)',
    'Lime-iro Senkitan: Nankoku Yume Roman',
    'Rita to Nantoka',
    'Dokidoki! Precure',
    'Hooligan',
    'Rewrite 2nd Season',
    'Hatena☆Illusion',
    'Kitsutsuki Keikaku',
    'Gegege no Kitarou (2007)',
    'Gakuen Handsome: Haitoku no Lesson',
    'Resort Boin',
    'Choujin Locke: Shinsekai Sentai',
    'Kage (OVA)',
    'Mainichi ga Nichiyoubi',
    'Tondemo Nezumi Daikatsuyaku',
    'Cooking Papa Christmas Special',
    'Youkaiden Nekome Kozou',
    'Sobakasu Pucchi',
    'Animal Yokochou',
    'Shikioriori',
    'Dakaretai Otoko 1-i ni Odosarete Imasu.',
    'Animegatari x Ghost in the Shell Collab Eizou',
    'Romeo x Juliet',
    'Chuntian Huahua Zhonghua Bowuguan',
    'Boruto: Naruto the Movie - Naruto ga Hokage ni Natta Hi',
    'Busou Shinki Moon Angel',
    'Kakushi Dere Special',
    'Little Nemo Pilot (1987)',
    'Nagi no Asukara',
    'Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Washi to Ore!? - Bokura wa Asakusa Shounen Tanteid',
    'Sankou to Tako: Hyakumanryou Chinsoudou',
    'Natsu no Ginkei',
    'on-chan, Yume Power Daibouken!',
    'Hajimete no Christmas',
    'Cheol-in 007',
    'Detective Conan: Happy New Year Special',
    'Tenjou Tenge: The Past Chapter',
    'Pichiko Dakyuubu USA-hen',
    'Shisha no Teikoku',
    'Otoko wa Tsurai yo: Torajirou Wasurenagusa',
    'Final Fantasy VII: Advent Children',
    'Ghost in the Shell: Stand Alone Complex 2nd GIG - Individual Eleven - Tachikoma no Hibi',
    'Yuuki Hitotsu wo Tomo ni Shite',
    'Dies Irae',
    'Mellow',
    'Baito-saki wa "Aku no Soshiki"!?',
    'Tenshi no Shippo Chu!: Tenshi no Utagoe',
    'Tales of Symphonia The Animation: Sekai Tougou-hen',
    'Shusaku Liberty',
    'Rokudenashi Majutsu Koushi to Akashic Records',
    'Shiroi Zou',
    'Future Card Buddyfight',
    'Ibara-Hime matawa Nemuri-Hime',
    'Furiko',
    'Neko mo, Onda-ke',
    'Aa! Megami-sama!: Chichaitte Koto wa Benri da ne',
    'Kero Kero Keroppi no Gulliver no Bouken',
    'Trouble Chocolate',
    'Okane wa Mawaru: Kurashi to Kinyuu',
    'HeatGuy J',
    'Gakuen Handsome: Legend of Sexy',
    'Fortune Quest L',
    'Paniponi Dash!: Danjite Okonaeba Kishin mo Kore wo Saku',
    'E no Umakatta Tomodachi',
    'Kantoku Fuyuki Todoki',
    'Akiba&#039;s Trip The Animation',
    'Kyoufu no Bio Ningen Saishuu Kyoushi',
    'Hiroshima e no Tabi',
    'Rinkan Gakuen: Yamete! ...Okaasan, Minaide!',
    'Yoru wa Mijikashi Arukeyo Otome',
    'Higanjima X: Aniki',
    'Shin Chou Kyou Ryo: Condor Hero II',
    'Yume-iro Pâtissière: Mune Kyun Tropical Island!',
    'Kyou, Koi wo Hajimemasu',
    'Banana Mura ni Ame ga Furu',
    'Yonimo Osoroshii Grimm Douwa',
    'Manga Nihonshi',
    'Hakushon Daimaou',
    'Xiao Qian',
    'Miracle Psychicer Seizan',
    'High School DxD New: Oppai, Tsutsumimasu!',
    'Kyoukai no Kanata',
    'Zettai Junpaku♡Mahou Shoujo',
    'Pretty x Cation 2 The Animation',
    'Muteki Choujin Zanbot 3',
    'The New A-Class.: Next Stage with YOU',
    'Ys',
    'Koisuru Tenshi Angelique: Kagayaki no Ashita Special',
    'Mama Gomennasai',
    'Blend S',
    'Natural 2: Duo',
    'Prison Bear',
    'Rozen Maiden: Ouvertüre',
    'Lady Lady!!',
    'Ofuro no Kazoe Uta',
    'Inazuma Eleven: Chou Jigen Dream Match',
    'Urusei Yatsura: Haru da, Tobidase!',
    'Shingeki no Kyojin Movie 1: Guren no Yumiya',
    'Crystal Blaze',
    'Non Non Biyori',
    'Kaiketsu Zorro',
    'UFO Robo Grendizer',
    'Maji de Otaku na English! Ribbon-chan: Eigo de Tatakau Mahou Shoujo - The TV',
    'Shin Koihime†Musou: Live Revolution',
    'Akichi Asobi: Playground',
    'Infini-T Force',
    'Ninja Bugei-chou',
    'Senjutsu Choukoukaku Orion',
    'Hyakko',
    'Hime Chen! Otogi Chikku Idol Lilpri',
    'Regalia: The Three Sacred Stars',
    'Space Gundam V',
    'Metal Fight Beyblade: Baku',
    'Ghost in the Shell: Arise - Another Mission',
    'Koi wa Ameagari no You ni',
    'Shimajirou to Ookinaki',
    'Utsunomiko',
    'Hagane Orchestra',
    'Watashi ga Motenai no wa Dou Kangaetemo Omaera ga Warui!',
    'Madonna (Movie)',
    'Komadori Eiga: Komaneko',
    'Fujun Isei Kouyuu: Taisetsu na Kimi e',
    'Legendz: Yomigaeru Ryuuou Densetsu',
    'Princess Princess Specials',
    'Genki Genki Non-tan: Spoon Tan Tan Tan',
    'Akubi Girl',
    'Yuri Seijin Naoko-san (2012)',
    'Koi Hanabi',
    'A.F',
    'Robot Taekwon V',
    'Waver',
    'Minna de Bokumetsu Inshu Unten',
    'Toaru Kagaku no Railgun S: Motto Marutto Railgun',
    'Moufu no Hi',
    'Cosmic Baton Girl Comet-san☆',
    'Oyome-sama Honey Days♥',
    'Mutant Turtles: Choujin Densetsu-hen',
    '20-dai no Heya-hen',
    'Transformers Victory',
    'Joker: Marginal City',
    'Ie Naki Ko Remy Specials',
    'Yume wo Kanaeru Zou',
    'Seigi wo Aisuru Mono Gekkou Kamen',
    'Maze Maze Wien',
    'Overlord Picture Drama',
    'Street Fighter IV: Aratanaru Kizuna',
    'Kine-Pass Gekijou',
    'Hage',
    'Wan Wan Celepoo Soreyuke! Tetsunoshin',
    'Owari no Chronicle',
    'Seito Shokun! Kokoro ni Midori no Neckerchief wo',
    'Akazukin Chacha',
    'Yuuki Yuuna wa Yuushabu Shozoku 2',
    'Ba La La Xiao Mo Xian Zhi: Feiyue Cai Ling Bao',
    'The Night Game: Neko no Sakusen',
    'Ekimemo!',
    'Kero Kero Keroppi no Yowamushi-ouji no Daibouken',
    'Kitte no Nai Okurimono',
    'Marginal Prince: Gekkeiju no Ouji-tachi',
    'Genkichi Jiisan to Kogitsune',
    'Orenchi no Furo Jijou',
    'Mobile Suit Gundam SEED Destiny',
    'Angelique: Twin Collection',
    'Matsubara-kun',
    'Onsen Yousei Hakone-chan',
    'Sengoku Basara Movie: 4-Koma Gekijou - Another Last Party',
    'Samurai Hormone The Animation',
    'Shin Dokonjou Gaeru',
    'Gilgamesh',
    'Kaze no Tairiku',
    'Battle Spirits: Double Drive',
    'Bokura wa Minna Kawai-sou: Hajimete no',
    'Licca-chan to Mahou no Kuni',
    'Kataribe Shoujo Honoka',
    'Ninja Hattori-kun (2012) Special',
    'Uta no☆Prince-sama♪ Maji Love Legend Star',
    'Taka no Tsume GO: Utsukushiki Elleair Shoushuu Plus',
    'ef: A Tale of Memories. - Recollections',
    'Ichigo 100%',
    'Lupin III: Part 5',
    'Mobile Suit Gundam F91',
    '15 Bishoujo Hyouryuuki',
    'Arashi no Yoru ni',
    'Re Boot',
    'Tetsuwan Birdy Decode',
    '30-sai no Hoken Taiiku',
    'Rurouni Kenshin: Meiji Kenkaku Romantan - Shin Kyoto-hen',
    'Yoroiden Samurai Troopers Message',
    'Omakase! Miracle Cat-dan',
    'Kirakira☆Precure A La Mode Movie: Paritto! Omoide no Mille-Feuille!',
    'Akihabara Dennou-gumi',
    'Ingress',
    'Coluboccoro',
    'Aru Tabibito no Nikki Specials',
    'Show By Rock!!: Legend of Shingan Crimsonz',
    'Koukaku no Pandora',
    'Fujilog',
    'Shina Dark: Kuroki Tsuki no Ou to Souheki no Tsuki no Himegimi',
    'Hanabi',
    'Kachikachi Yama',
    'Kuroshitsuji II Specials',
    'Soukyuu no Fafner: Dead Aggressor - Exodus',
    'Jokei Kazoku III: Himitsu - The Anime',
    'Rockman.EXE',
    'Zan Sayonara Zetsubou Sensei Bangaichi',
    'Miss Monochrome: The Animation - Soccer-hen',
    'Hitozuma Life: One Time Gal',
    'Landreaall',
    'Hana no Kage',
    'Tamagawa Kyoudai',
    'Magical Nyan Nyan Taruto',
    'Masuda Kousuke Gekijou Gag Manga Biyori 2',
    'By Your Side',
    'Akuma no Kairozu',
    'Loups=Garous Picture Drama',
    'Feng Wei Ying Xiong',
    'Yotsunoha',
    'Pokemon XY&Z',
    'Kubbe PV Full ver.',
    'Heavy Object',
    'Owari no Seraph: Kyuuketsuki Shahar',
    'Osomatsu-kun',
    'Kamyla',
    'High School! Kimengumi (Movie)',
    'Scared Rider Xechs',
    'Catman',
    'Platonic Chain: Web',
    'Night Head Genesis',
    'Muu no Hakugei',
    'Shaonian Jinyiwei 2nd Season',
    'D-1 Devastator',
    'Uchuu Senshi Baldios',
    'Tomica Hyper Rescue Drive Head: Kidou Kyuukyuu Keisatsu (TV)',
    'Cerberus',
    'Moonlight Mile 2nd Season: Touch Down',
    'Hibike! Wadaiko',
    'Kaguya-hime no Monogatari',
    'THE iDOLM@STER Cinderella Girls: Starlight Stage - Shinshun! Happy New Year Campaign',
    'Ninkuu (Movie)',
    'Two Tea Two',
    'Dream Hazard: Akuma no Program',
    'Go-hiki no Kobuta to Charleston',
    'Shakugan no Shana: Shana & Yuuji no Naze Nani Shana! Nandemo Shitsumon-bako!',
    'Kara no Kyoukai: Manner Movies',
    'Futa-bu!!',
    'Hangyakusei Million Arthur',
    'Koiwai Junsui Kajuu: Bokura Junsui-hen',
    'Aqua Kids',
    'Soul Worker: Your Destiny Awaits',
    'Izumo',
    'PJ Berri no Mogumogu Munyamunya',
    'Hanasakeru Seishounen Recaps',
    'Goman-hiki',
    'Kämpfer',
    'Shiroi Michi',
    'Grand Marche no Meikyuu',
    'Makai Kishi Ingrid',
    'Witchblade',
    'The Borgman: Last Battle',
    'Bishoujo Senshi Sailor Moon R: The Movie',
    'Jishu Seisaku Movie Binchou-tan',
    'Hana no Hanashi',
    'Starmyu OVA (2018)',
    'Hyakka Ryouran: Samurai After',
    'Mahou Shoujo Lyrical Nanoha ViVid',
    'Uma no Friends',
    'Universe',
    'Zettai Bouei Leviathan',
    'Petit Petit Muse',
    'Hataraku Onii-san!',
    'Unbalance',
    'Cosplay Rakuen',
    'The Third: Aoi Hitomi no Shoujo',
    'Yahari Ore no Seishun Love Comedy wa Machigatteiru.',
    'Kamen Rider Den-O: Imagin Anime',
    'Isobe Isobee with Nakata Yasutaka de Sourou',
    'Pic-lele',
    'Onbu Obake',
    'Shingeki no Kyojin-ten 360° Taikan Theater',
    'Kagaku Ninja-tai Gatchaman II',
    'Shoujo Kakumei Utena: Adolescence Mokushiroku',
    'Ojiichan wa Boku no Hero',
    'The Midnight★Animal',
    'Ginga Eiyuu Densetsu Gaiden: Ougon no Tsubasa',
    'Sore Ike! Anpanman: Kokin-chan to Aoi Namida',
    'Visionary',
    'Nagagutsu wo Haita Neko no Bouken',
    'Mr. Bond',
    'Gabriel DropOut Specials',
    'Turn A Gundam II Movie: Moonlight Butterfly',
    'Mahou Shoujo Taisen',
    'Detective Conan OVA 06: Follow the Vanished Diamond! Conan & Heiji vs. Kid!',
    'Dropout',
    'Inagawa Junji no Sugo: Ku Kowai Hanashi',
    'Esoragoto Spiral',
    'Shichinin no Nana',
    'Kappa no Sanpei',
    'Ai wa Kagi no Kazu dake... Fuuzoku Mansion',
    'Tengen Toppa Gurren Lagann Movie: Lagann-hen Special - Viral no Amai Yume',
    'Hajime no Ippo: Boxer no Kobushi',
    'Netoge no Yome wa Onnanoko ja Nai to Omotta?',
    'Shin Tenchi Muyou!',
    'Yojouhan Shinwa Taikei',
    'Samuraider: Nazo no Tenkousei',
    'Maze',
    'Yukiyo Ichiya Monogatari',
    'Kore wa Zombie Desu ka? of the Dead',
    'Bounty Hunter: The Hard',
    'Techno Police 21C',
    'Peach Girl',
    'Toilet no Hanako-san',
    'Kobayashi-san Chi no Maid Dragon: Valentine, Soshite Onsen! - Amari Kitai Shinaide Kudasai',
    'Gunjou no Magmel',
    'Prism Ark',
    'Evil or Live',
    'Saa Ikou! Tamagotchi',
    'Taka no Tsume-dan, Toyama',
    'Oyayubi Hime Monogatari',
    'Shinjuku Shin-chan Patrol: Warui Otona ni Ki wo Tsukete',
    'K-On!!: Ura-On!!',
    'Macross F Movie 2: Sayonara no Tsubasa',
    'Munto: Toki no Kabe wo Koete',
    'Jakusansei Million Arthur Specials',
    'Pokemon XY: Mega Evolution',
    'Nyan Koi!',
    'Kiki to Lala no Habatake! Pegasus',
    'Eguchi Hisashi no Nantoka Narudesho!',
    'Akai Kutsu! Onnanoko!',
    'Accel World: Infinite∞Burst',
    'Puchimas!: Petit iDOLM@STER Episode 0',
    'Umi no Mizu wa Naze Karai',
    'Kuusou no Sora Tobu Kikaitachi',
    'Iron Man: Rise of Technovore',
    'Alien 9',
    'Kokoro no Chikara',
    'Kao no nai Tsuki',
    'Zephyr',
    'Direct Animation',
    'Uchuu Ace',
    'Yancharu Moncha',
    'Star Ocean EX',
    'Akai Koudan Zillion',
    'Angelique: Shiroi Tsubasa no Memoire',
    'Midnight Crazy Trail',
    'Akihabara Dennou-gumi: 2011-nen no Natsuyasumi',
    'Blassreiter',
    'Baka Baka Baka na Sekai',
    'Haiyore! Nyaruko-san',
    'Eto wa Merry-Go-Round',
    'Samurai Girl Real Bout High School',
    'Tenchi Muyou! in Love',
    'Osomatsu-kun (1988): Appare! Chibita no Onitaiji zansu',
    'Moshidora Recap',
    'Gegege no Kitarou: Kitarou no Yuurei Densha',
    'Ryou Seibai!: Gakuen Bishoujo Seisai Hiroku',
    'Bokura no Live Kimi to no Life',
    'Pony Metal U-GAIM Promotion Film',
    'Marin X',
    'Naniwa Kinyuu Den: Minami no Teiou',
    'Yoshida no Matsue Beauty Daisakusen Prologue',
    'Rennyo to Sono Haha',
    'Jijii: Owari no Hajimari',
    'Toshi wo Totta Wani',
    'Shiofuki Mermaid',
    'Shiawase Haitatsu Taneko',
    'Shinkyoku Soukai Polyphonica Crimson S',
    'Pata Pata Mama',
    'PoPo Loouise',
    'Hi no Tori: Yamato-hen',
    'Ongaku Shoujo (TV)',
    'Dagashi Kashi 2',
    'Kaguya-hime: Taketori Monogatari',
    'Ensemble Stars! The Animation',
    'Hyakuren no Haou to Seiyaku no Valkyria',
    'Maison Ikkoku: Kanketsu-hen',
    'Ultraviolet: Code 044',
    'Escalator-jou no Hokou no Kiken-sei',
    'Shinshuu Sudama-hen',
    'Crayon Shin-chan Movie 02: Buriburi Oukoku no Hihou',
    'Carino Coni',
    'Oh! 96-kku',
    'Manyuu Hikenchou',
    'G-Taste (2010)',
    'Dragon Ball Super Movie',
    'Days (TV) OVA',
    'Swing Out Sisters (2014)',
    'Yomiuri Shimbun',
    'Dokidoki♡Densetsu: Mahoujin Guruguru',
    'Muybridge no Ito',
    'Terra e... (TV) Specials',
    'Qin Shi Ming Yue: Guoqing Tebie Pian',
    'Shoujo Senki Soul Eater',
    'Cinderella Girls Gekijou 3rd Season',
    'Good Morning',
    'Perman: Birdman ga Yatte Kita!!',
    'Anime Oyako Gekijou',
    'Tanukichi no Ohanashi',
    'Hanamaru Youchien',
    'Perman',
    'Rhythm',
    'Chikkun Takkun',
    'Norman the Snowman: Kita no Kuni no Aurora (Kari)',
    'Zoku Natsume Yuujinchou: 3D Nyanko-sensei Gekijou',
    'Momotarou',
    'Seiken no Blacksmith',
    'Zukkoke Sannin-gumi: Zukkoke Jikuu Bouken',
    'Mahou no Yousei Persia Pilot',
    'Mameshiba Gakuen',
    'Magnerobo Ga-Keen',
    'Mahoutsukai Sally',
    'Cabbage UFO',
    'Ichigeki Sacchuu!! Hoihoi-san',
    'La Primavera',
    'Shinryaku!? Ika Musume',
    'Mashin Eiyuuden Wataru 2',
    'Dragon Pink',
    'Meng Qi Shi Shen',
    'Gan Gan Ganko-chan 2nd Season',
    'Kawaii Cook-san',
    'Quiz Magic Academy: The Original Animation',
    'ViVid Strike!',
    'Basilisk: Ouka Ninpouchou',
    'Sonic: Night of the WereHog',
    'Chibo',
    'Saraiya Goyou',
    'Kimi no Kokoro wa Kagayaiteru kai?',
    'The TV Show',
    'Dororon Enma-kun',
    'Lupin III: Green vs. Red',
    'Ling Qi',
    'Nae Ireumeun Dokgotak',
    'GR: Giant Robo',
    'Drill',
    'Namakura Gatana',
    'Happy☆Lesson: Advance',
    'Rurouni Kenshin: Special Techniques',
    'Sore Ike! Anpanman: Lyrical☆Magical Mahou no Gakkou',
    'Rokudou Juku',
    'Kozaru no Buranko',
    'Future War 198X-nen',
    'Shounen Hollywood: Holly Stage for 50',
    'Kumo ni Noru',
    'Tennis no Ouji-sama: Oshougatsu Special',
    'Densetsu Kyojin Ideon',
    'Senyuu. Specials',
    'Baby Princess 3D Paradise 0 [Love]',
    'Kaibutsu-kun: Kaibutsu Land e no Shoutai',
    'Maid Ane',
    'Ore ga Ojousama Gakkou ni "Shomin Sample" Toshite Gets♥Sareta Ken',
    'Kaeru San Yuushi',
    'Love Bitch: Yasashii Onna',
    'Rokujouma no Shinryakusha!? (TV)',
    'Taiyou no Yuusha Fighbird',
    'Tsubu★Doll',
    'Kurutta Kyoutou: Danzai no Gakuen',
    'Hey! Bumboo',
    'Eureka Seven AO: Aratanari Fukaki Ao',
    'From Osaka with Cheer!',
    'Nurse Angel Ririka SOS',
    'Eien no Aselia',
    'Nama Lo Re: Namakemono The Animation',
    'MTV Ident: Horny',
    'Osakana wa Ami no Naka',
    'Sore Ike! Anpanman: Rhythm de Teasobi - Anpanman to Fushigi na Parasol',
    'Yuri!!! on Ice: Yuri Plisetsky GPF in Barcelona EX - Welcome to The Madness',
    'Ai no Kusabi (2012)',
    'Monster Strike: Zoku Saishuu-banashi - Pandora no Hako',
    'Urusei Yatsura OVA',
    'Love² Police',
    'Eiyuu Densetsu: Sora no Kiseki The Animation',
    'Kidou Senshi Gundam Narrative',
    'Magical Moe',
    'Ame-iro Cocoa: Rainy Color e Youkoso!',
    'Residence',
    'Kareshi Kanojo no Jijou',
    'Senkou no Night Raid Specials',
    'One Piece Movie 8: Episode of Alabasta - Sabaku no Oujo to Kaizoku-tachi',
    'An Expression',
    'Gakkyuu Ou Yamazaki Specials',
    'Ancien to Mahou no Tablet: Mou Hitotsu no Hirune Hime',
    'Mikagura Gakuen Kumikyoku (TV)',
    'The Kabocha Wine: Nita no Aijou Monogatari',
    'IDOLiSH7 Tokubetsu Bangumi: Kimi to Furikaeranaito!',
    'Gintama°: Aizome Kaori-hen',
    'Norakuro Ittouhei',
    'Commercial War',
    'Mina no Egao',
    'Mai-HiME Specials',
    'Guilty Crown: Lost Christmas',
    'Jigoku Shoujo Mitsuganae',
    'Haja Kyosei G Dangaiou',
    'Boku no Hero Academia The Movie: Futari no Hero',
    'Deltora Quest',
    'Doraemon Movie 15: Nobita to Mugen Sankenshi',
    'Dorami-chan: A Blue Straw Hat',
    'Hime Chen! Otogi Chikku Idol Lilpri (2011)',
    'Nukko.',
    'Qingwa Wangguo: Zhi Bingdong Da Maoxian',
    'Hitsugi no Chaika',
    'Clannad Movie',
    'Tanin no Kankei',
    'Ojamajo Doremi Na-i-sho',
    'Ninja Hattori-kun',
    'UQ Holder!: Mahou Sensei Negima! 2',
    'Monotonous Purgatory',
    'Seme♥Chichi',
    'Zombie-Loan',
    'R.O.D OVA',
    'Pokemon XY: Koukoku no Princess Diancie',
    'Majime ni Fumajime Kaiketsu Zorori',
    'Washimo',
    'Amagami SS+ Plus',
    'Chinka',
    'Keraku-No-OH King of Pleasure',
    'Huyao Xiao Hongniang: Qian Yan',
    'Sougiya to Inu',
    'Inazuma Eleven Go: Galaxy',
    'Ukare Violin',
    'Solty Rei',
    'Toumei Ningen (OVA)',
    'Natsu-iro no Sunadokei',
    'Akuemon',
    'Natsuyasumi.',
    'Tenchi Muyou! Ryououki 2nd Season Picture Drama',
    'Crayon Shin-chan Movie 21: Bakauma! B-Kyuu Gourmet Survival Battle!!',
    'Aquarion Logos',
    'Tales of Gekijou',
    'Shinken Seminar Koukou Kouza',
    'Owarimonogatari',
    'Hakumei to Mikochi: Neji to Bed to Irori to Bakuchi',
    'Tales of Zestiria: Doushi no Yoake',
    'Nana Moon',
    'Doraemon Movie 07: Nobita to Tetsujin Heidan',
    'Futari Daka',
    'Cream Lemon',
    'Kidou Keisatsu Patlabor: New OVA',
    'Teekyuu 2 Specials',
    'Rockman.EXE Axess',
    'Hikaru no Go: Tokubetsu-hen - Sabaki no Ichikyoku! Inishie no Hana yo Sake!!',
    'Hello Kitty no Nagagutsu wo Naita Neko',
    'Marvel Disk Wars: The Avengers',
    'Mobile Suit Gundam 0080: War in the Pocket',
    'Kamisama no Memochou',
    'Soccer Fever',
    'Glass no Kamen Desu ga to Z Specials',
    'Detective Conan OVA 05: The Target is Kogoro! The Detective Boys&#039; Secret Investigation',
    'Seikimatsu Leader Gaiden Takeshi!',
    'Beppu x Peeping Life',
    'Crusher Joe OVA',
    'Cinderella Boy',
    'Masaru Ashita no Yukinojou 2',
    'Panda-Z: The Robonimation',
    'Sanctuary',
    'Sengoku Choujuu Giga: Kou',
    'Shounen Ashibe: Go! Go! Goma-chan 2',
    'Sexfriend',
    'Valkyrie Choukyou Semen Tank no Ikusa Otome 10-nin Shimai',
    'Dr. Slump Movie 02: "Hoyoyo!" Uchuu Daibouken',
    'Haja Taisei Dangaiou',
    'Highway Jenny',
    'Rainbow no Anime Bako',
    'Himitsukessha Taka no Tsume The Movie 3: http://takanotsume.jp wa Eien ni',
    'Tantei Opera Milky Holmes Dai 2 Maku',
    'Q Transformers: Kaette Kita Convoy no Nazo',
    'Huyao Xiao Hongniang: Wangquan Fugui',
    'Detective Conan: A Written Challenge from the Pyramids!',
    'Precure All Stars Movie: Haru no Carnival♪ - Ima Koko kara',
    'Great Rabbit',
    'Bunna yo Ki kara Orite Koi',
    'Youyou no Neko Tsumami',
    'Generation of Chaos Next: Chikai no Pendant',
    'Soukou Kihei Votoms: Pailsen Files the Movie',
    'Love Position: Halley Densetsu',
    'Jigoku de Naze Warui',
    'Urameshi Denwa',
    'Tatakae! Chou Robot Seimeitai Transformers',
    'Stella Jogakuin Koutou-ka C³-bu',
    'Anata ga Furikaeru Toki',
    'Suteki desu wa, Sakura-chan! Tomoyo no Cardcaptor Sakura Katsuyaku Video Nikki!',
    'Ooatari Sora no Entaku',
    'Mai-Otome Zwei Special',
    'Sweat Punch',
    'Cinnamon no Parade',
    'Koihime',
    'Naked Wolves',
    'Juuni Senshi Bakuretsu Eto Ranger',
    'Kai Douryoku Real',
    'Sore Ike! Anpanman: Sukue! Kokorin to Kiseki no Hoshi',
    'Hunter x Hunter Movie 1: Phantom Rouge',
    'Eguchi Hisashi no Kotobuki Gorou Show',
    'Shigeo wa Handsome',
    'Kero Kero Keroppi no Sora wo Tobetara',
    'Tejina Shi',
    'Ichinen Buri no The Animation',
    'Rinne no Lagrange Season 2 Specials',
    'Hitozuma Koukan Nikki',
    'Jikkyou Chuukei',
    'M3: Sono Kuroki Hagane Recap',
    'Soukyuu no Fafner: Dead Aggressor - Heaven and Earth',
    'Kenja no Mago',
    'Saimin Class',
    'Yasashii March: The Tender March',
    'Agigongryong Doolie',
    'Gekkan Shoujo Nozaki-kun Specials',
    'Fuusen Inu Tinny 2nd Season',
    'Kouchuu Ouja Mushiking: Greatest Champion e no Michi',
    'Ginga Hyouryuu Vifam: Kachua Kara no Tayori',
    'Elysium',
    'Yu☆Gi☆Oh! Duel Monsters: Battle City Special',
    'McDull: Xiang Dang Dang Ban Wo Xin',
    'Can Can Bunny Extra',
    'Hi no Ame ga Furu',
    'Inaka Nezumi to Machi Nezumi',
    'Moekan The Animation',
    'Ippatsu Kanta-kun',
    'Hello Kitty no Happy! Kasou Taikai',
    'Detective Conan Movie 18: The Sniper from Another Dimension',
    'Teekyuu 2',
    'Ore no Imouto ga Konnani Kawaii Wake ga Nai: SD Chara ni Yoru Character Commentary',
    'Tu Xia Chuanqi',
    'Love♥Love? Specials',
    '07-Ghost',
    'Captain Future: Kareinaru Taiyokei Race',
    'Inemuri Buu-chan',
    'Santa Company',
    'Zeonic Toyota Special Movie',
    'Nakoruru: Ano Hito kara no Okurimono',
    'Pokemon Housoukyoku',
    'Stone Age',
    'Doraemon Movie 20: Nobita no Uchuu Hyouryuuki',
    'The☆Doraemons: Mushimushi Pyonpyon Daisakusen!',
    'D+vine Luv',
    'Ninpou Midare Karakuri',
    'Otanoshimi Anime Gekijou',
    'Jarujio Animal',
    'Natsufuku no Shoujo-tachi',
    'BanG Dream!: Asonjatta!',
    'Fire Emblem',
    'Hayabusa: Back to the Earth - Kikan',
    'Dokidoki Gakuen Kessen!! Youki Daimashiro',
    'Appleseed (Movie)',
    'Hong Kil-dong',
    'Show By Rock!! Short!!',
    'Bonobono (2016)',
    'Karo to Piyobupt: Ame no Hi',
    'Mesu Nochi Torare',
    'Alexander Senki Movie',
    'Donguri Mori e',
    'Digimon Savers 3D: Digital World Kiki Ippatsu!',
    'Poker',
    'Chicchana Yukitsukai Sugar Specials',
    'Ai no Wakakusa Yama Monogatari',
    'Kero Kero Keroppi no Bikkuri! Obakeyashiki',
    'Doraemon Movie 34: Shin Nobita no Daimakyou - Peko to 5-nin no Tankentai',
    'Kitsune Tsuki',
    'Licca-chan no Nichiyoubi',
    'Shikabane Hime: Kuro – Soredemo, Hito to Shite',
    'Lilt',
    'Rance 01: Hikari wo Motomete The Animation - Leazas no Yami',
    'Rayca',
    'Imouto Twins',
    'himitsukesshatakanotsume.jp Specials',
    'Momotaros no Natsuyasumi',
    'Poron Guitar',
    'Manga Doushite Monogatari OVA',
    'Kaitou Tenshi Twin Angel: Kyun Kyun☆Tokimeki Paradise!!',
    'Hijikata Toshizou: Shiro no Kiseki',
    'Dirty Pair',
    'Nanocore',
    'Manyuu Hikenchou Specials',
    'Ai to Shi',
    'Pandora Hearts Specials',
    'Ra/Radio Noise*Planet',
    'After School',
    'Sinbad: Mahiru no Yoru to Fushigi no Mon',
    'Ze Tian Ji',
    'Baka to Test to Shoukanjuu: Matsuri - Sentakushi Ikou nomi',
    'Kero Kero Keroppi no Ganbare! Keroppooz',
    'Mononoke Hime',
    'Dennou Coil Recaps',
    'Samurai Giants',
    'K: Seven Stories Movie 6 - Circle Vision - Nameless Song',
    'Mattsu to Yanma to Moburi-san 2: Suigun Otakara to Nazotoki no Shimajima',
    'Tenshi ni Narumon!',
    'Strawberry Panic',
    'Vanquished Queens Specials',
    'Stone',
    'Hakuouki Reimeiroku',
    'Hello Kitty no Santa-san ga Futari Ita',
    'Xiong Chumo Zhi: Conglin Zongdongyuan',
    'Crayon Shin-chan Movie 12: Arashi wo Yobu! Yuuhi no Kasukabe Boys',
    'Lamune',
    'Yume de Aetara (TV)',
    'Konbini Kareshi',
    'Furifure The Animation',
    'Rakuen Tsuihou',
    'Sailor Fuku Shinryou Tsumaka',
    'El Cazador de la Bruja',
    'Kaibutsu Oujo (OVA) Specials',
    'Little Busters!: Refrain',
    'Kamiusagi Rope & Taka no Tsume Collab Eizou-hen',
    'Ikusa Otome Valkyrie 2',
    'Aoki Ryuusei SPT Layzner OVA',
    'Metal Fight Beyblade Zero G Specials',
    'Nagato Yuki-chan no Shoushitsu: Owarenai Natsuyasumi',
    'Gantz',
    'Kyuukyoku Choujin R',
    'Yoshinaga-san&#039;chi no Gargoyle',
    'Xian Yue Meng Ying',
    'Buzzer Beater 2nd Season',
    'Gun x Sword-san',
    'Bakegyamon',
    'Eightman',
    'Dirty Pair Flash 2',
    'Mori no Densetsu: Dai Ni Gakushou',
    'Zenmaiji-kake no Truffe',
    'Seitokaichou Hikaru',
    'Time Bokan Series: Zenderman',
    'Cinderella Girls Gekijou: Kayou Cinderella Theater 3rd Season',
    'Vatican Kiseki Chousakan OVA',
    'Sinbad: Mahou no Lamp to Ugoku Shima',
    'Domo-kun',
    'Planetarian: Hoshi no Hito',
    'Teizokurei Daydream',
    'Comet Lucifer',
    'Pokemon: Maboroshi no Pokemon Lugia Bakutan',
    'Dragon Ball Z Movie 10: Kiken na Futari! Super Senshi wa Nemurenai',
    'Sekai no Yami Zukan',
    'Shiodome Cable TV',
    'Watashi no Naka no Gensou-teki Sekaikan Oyobi Sono Kengen wo Souki Saseta Aru Genjitsu de no Dekigot',
    'Fruits 5 Shimai',
    'Yeongsimi',
    'Ragnastrike Angels',
    'Good Morning Call',
    'Ookami Heart',
    'Minamo',
    'Video Ehonkan Sekai Meisaku Douwa',
    'Riding Bean',
    'Niizuma Koyomi The Animation',
    'Ladies versus Butlers!',
    'Kuma Miko',
    'Dragon Quest: Dai no Daibouken',
    'Tonari no Oneesan',
    'One Piece: Mezase! Kaizoku Yakyuu Ou',
    'Shoko Nakagawa Prism Tour Special',
    'Gambo',
    'Toradora!: SOS!',
    'Masuda Kousuke Gekijou Gag Manga Biyori 3',
    'Keitai Shoujo',
    'Koisuru Shirokuma',
    'Dimension W: W no Tobira Online',
    'El Hazard: The Magnificent World',
    'Norasco: Cinema Point Card-hen',
    'Shikkoku no Shaga The Animation',
    'Blind Night',
    'Bishoujo Senshi Sailor Moon Memorial',
    'Koisuru Tenshi Angelique: Kagayaki no Ashita',
    'Shakugan no Shana III (Final)',
    'Huyao Xiao Hongniang',
    'Issunboushi',
    'Okore!! Nonkuro',
    'Megazone 23',
    'Koukyoushihen: Eureka Seven - Hi-Evolution 2',
    'Grand Blue',
    'High School Fleet Movie',
    'Macross F Music Clip Shuu: Nyankuri',
    'Sumiko no Egao',
    'Grappler Baki: Saidai Tournament-hen',
    'Attack No.1: Namida no Sekai Senshuken',
    'Pururun! Shizuku-chan Aha',
    'Chu^2',
    'Minna Agechau♡',
    'Kyuuketsuhime Miyu (TV)',
    'Bondage Game: Shinsou no Reijoutachi - Shinsou no Doreitachi',
    'Ecchies',
    'Heart Cocktail',
    'Sore Ike! Anpanman: Anpanman to Happy Otanjoubi',
    'Wo Shi Na Zha',
    'Koro-sensei Q!',
    'Macross Δ Movie: Gekijou no Walküre',
    'Komori-san wa Kotowarenai!',
    'Saikyou Bushouden: Sangoku Engi',
    'Ranma ½: Battle ga Ippai 29-nin no Korinai Yatsura',
    'Planetes',
    'Nekota no Koto ga Kininatte Shikatanai. (ONA)',
    'Kono Danshi, Sekika ni Nayandemasu.',
    'Mimi wo Sumaseba',
    'Zoids Wild',
    'Geori-eui Mubeopja',
    'Hatsukoi Limited.: Gentei Shoujo',
    'Esper Mami',
    'Neko no Sumu Shima',
    'Zombie Ehon',
    'One Piece: Straw Hat Theater',
    'Sugar Bunnies Fleur',
    'Next Senki Ehrgeiz',
    'Ichiban Ushiro no Daimaou Specials',
    'Ninja Slayer From Animation',
    'Battle Spirits: Sword Eyes Gekitouden',
    'Fireball Charming',
    'Futakoi Alternative',
    'Persona 3 the Movie 1: Spring of Birth',
    'Sacred Seven: Shirogane no Tsubasa',
    'Petting a Dog',
    'Tsuki no Sango',
    'Ys: Tenkuu no Shinden - Adol Christine no Bouken',
    'Classical Sex-Zone',
    'Slayers Return',
    'Campus',
    'Hope: Suiso Shakai to, Korekara no Energy no Hanashi',
    'Cencoroll',
    'Zettai Karen Children',
  ].map((anime) => {
    return {
      title: anime,
      id: uuidv4(),
      url: `/${slugify(anime, {
        lower: true,
        strict: true,
      })}`,
    };
  });
};
